config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  post '/tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy', as: 'delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# Task Model
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <% if task.persisted?() %>
    <%= f.input :completed %>
  <% end %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">

  <h1>Edit task</h1>

  <%= render 'form', task: @task %>

</div>

app/views/tasks/index.html.erb
<h1>My Tasks list</h1>

<ul>

<% @tasks.each do |task| %>
    <li> <input type="checkbox" <% if task.completed? %>checked <% end %>> <%= link_to task.title,  task_path(task) %> -- <%= link_to '     🗑', delete_path(task), method: :delete, data: { confirm: "Are you sure to delete the task: #{task.title}?" }%></li>
  <% end %>
</ul>

<%=  link_to "Create new task", tasks_new_path %>

<button class="btn btn-primary"> TEST</button>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Create new task</h1>
  <%= render 'form', task: @task %>
</div>

app/views/tasks/show.html.erb
<h1> <%= @task.title %></h1>

<p> <%= @task.details %></p>

<%= link_to "Edit task", edit_path(@task) %>

<% if @task.completed? %>
  <p><input type="checkbox" checked> This task is completed</p>
<% else %>
  <p><input type="checkbox"> This task is NOT completed</p>
<% end %>

<%= link_to 'Back to tasks list', tasks_path %>